version: '3.4'

services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'stock_exchange_db'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    expose:
      - '3306'
   
